### ISSUE TITLE
Dropping a `Stream` / `Body` should reset it

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#100]
When all handles related to a stream are dropped, interest has been canceled. If the stream has not yet been closed, this should result in a `RST_STREAM` being sent out.

Originally from #75
Relates to #95

**Comment by hawkw** [comment]
I'd be happy to start on this?

**Comment by carllerche** [comment]
Sure

**Comment by nox** [comment]
This was implemented in #109.
