### ISSUE TITLE
expose APIs to set target window size

### ISSUE THREAD

**Issue by olix0r** [carllerche/h2#101]
There is no API to change the target window size to be different from SETTINGS_INITIAL_WINDOW_SIZE.  An endpoint may wish to this on either a connection or individual stream.

Clients, servers, and their streams should probably have `window_target(&self) -> u32` and `set_window_target(&mut self, sz: u32)` functions.

**Comment by seanmonstar** [comment]
So, several things do currently have methods like `release_capacity`, which will eventually lead to a `WINDOW_UPDATE` sent to the peer. It currently asserts that the amount "released" was previously received, but if that assertion were not in place, the `release_capacity(100_000)` could essentially send an update giving the peer that much window space...

Perhaps it is best to keep them separate, so as to be more explicit when someone is staying with the `INITIAL_WINDOW_SIZE`, and when someone is granting more than that...

**Comment by carllerche** [comment]
I don't think it would be exactly correct as `release_capacity(100_000)` would break the how the connection manages assigning connection level capacity (I think). Either way, I believe that the right way is to set target windows per stream and connection.
