### ISSUE TITLE
Support configuration of max_concurrent_streams

### ISSUE THREAD

**Issue by olix0r** [carllerche/h2#106]
`server::Builder` should support `set_max_concurrent_streams(&mut self, u32)` so that a server can constrain the number of streams per client.

Similarly, `client::Builder` should have this, though I _think_ a client can only configure the number of concurrent server-initiated streams (i.e. Push Promises).  While we're here, `client::Builder` should probalby also have a `set_push_promise_enabled(&mut self, bool)`

**Comment by seanmonstar** [comment]
>  While we're here, `client::Builder` should probably also have a `set_push_promise_enabled(&mut self, bool)`

There's `builder.enable_push(bool)`: https://github.com/carllerche/h2/blob/6ec7f38cd7378a6d99ab4300a07763ab1722dcb4/src/client.rs#L181

**Comment by carllerche** [comment]
Looks good to me.

**Comment by hawkw** [comment]
Started (9a4204b379a3ef7d9d9c4fec0eb238d85411c771), working on tests.
