### ISSUE TITLE
panic on invalid :authority

### ISSUE THREAD

**Issue by olix0r** [carllerche/h2#120]
When the value of `:authority` is invalid, we get the following panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUriBytes(InvalidUri(InvalidUriChar))', src/libcore/result.rs:906:4

   9: core::result::unwrap_failed
  10: <h2::server::Peer as h2::proto::peer::Peer>::convert_poll_message
  11: <h2::proto::connection::Connection<T, P, B>>::poll2
  12: <h2::server::Server<T, B> as futures::stream::Stream>::poll
```

This should probably be a User error and not a panic.

**Comment by seanmonstar** [comment]
Looks like this is in server, so it wouldn't be a user error.

> Endpoints MUST treat a request or response that contains undefined or invalid pseudo-header fields as malformed.

If we say that a `:authority` with illegal bytes is an "invalid pseudo-header", then it's a [stream error of PROTOCOL_ERROR](http://httpwg.org/specs/rfc7540.html#malformed).

**Comment by carllerche** [comment]
I think other "invalid request" situations are handled as a stream error currently.
