### ISSUE TITLE
After sending a RST_STREAM, inbound frames on that stream ID should be discarded for "some time"

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#130]
Currently, if a `RST_STREAM` is sent, the stream state transitions to closed and the state is dropped (once ref counts & queue counts go to zero).

However, the remote may not have acknowledged the `RST_STREAM` and may have frames already sent on the wire. Those frames must be silently dropped for "some time" allowing the remote to ack the reset.

**Comment by seanmonstar** [comment]
Is this a dupe of #74?

**Comment by carllerche** [comment]
Ah yes... good call. Closing

**Comment by carllerche** [comment]
I had only looked at the 0.1 milestone issues before filing this.
