### ISSUE TITLE
Handle `Stream` dropped before end-of-stream flag sent

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#138]
This is a continuation of [a comment](https://github.com/carllerche/h2/pull/109/files#r143109861).

I believe that currently, if a `Stream` is dropped without sending an end-of-stream flag, nothing happens. This would cause the stream to enter a hung state.

**Comment by seanmonstar** [comment]
We have to guess at the intent of the user here. 

- If there was a content-length set, and it's gotten to zero, then that's easy: send a 0-length EOS frame.
- If there was a content-length set, and it's not at zero yet, then the stream should be reset (probably with a CANCEL code).
- If no content-length was set, then I'm not sure which is correct. Do we guess that the user is just done? Or is it more appropriate to assume the stream should be reset unless explicitly finished?

**Comment by seanmonstar** [comment]
- With the client, it probably shouldn't reset unless the user also dropped the response future/stream, in which case dropping all stream refs triggers a cancel anyways.
- With the server, I'm still not certain whether it's more correct to send a reset or an empty EOS data frame.

**Comment by carllerche** [comment]
IMO for something like h2, I would be happy to say that the lib shouldn't maintain additional state to guess the right action here. Instead, it is up to the user to include an EOS flag at the end of the stream. Higher level libs should hide this detail from their users.

**Comment by seanmonstar** [comment]
So, unequivocally send a reset of `CANCEL`, always?

**Comment by carllerche** [comment]
I would say that would be preferable to hanging the stream and I don't think we should track additional state. It may be that the library already has enough state to do the right thing, but I am not sure off the top of my head.

So, in short:

* Don't track additional state for this issue
* Do the best thing possible, even if that is always sending a RST_STREAM with CANCEL.
