### ISSUE TITLE
Rename `server::Server` -> `Accept` or `Listener`

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#154]
This type is mostly used to acquire new H2 streams.

This is fairly low priority, but I thought I would propose the change to see what others thought about it.

**Comment by carllerche** [comment]
I'm on the fence about this. Does @olix0r have any thoughts?

**Comment by olix0r** [comment]
i think `Server` and `Client` should be equivalent... So if we're reserving `Client` for something higher up the stack, I think we should save `Server` as well.  I think either `Accept` or `Listener` is fine (and I'd look to the client side to determine how to name them  -- Connect/Accept, Connector/Listener, etc)

**Comment by carllerche** [comment]
Ok, here is my latest proposal.

* We reserve `Server` and `Client` names for hopefully something more fitting.
* `server::Server` -> `server::Connection`
* `client::Client` -> `client::SendRequest`. (there already is a `client::Connection`, which is correct).

**Comment by seanmonstar** [comment]
I don't love `SendRequest`, but admittedly there isn't much of a better name. `client::Handle`? :trollface:

**Comment by carllerche** [comment]
I declare a moratorium on naming things Handle!
