### ISSUE TITLE
Code coverage is causing CI to hang.

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#156]
Example build: https://travis-ci.org/carllerche/h2/jobs/288862038

I am going to remove it until we can figure out how to fix it.

**Comment by carllerche** [comment]
CI is having a number of spurious timing related failures. I wonder if travis is running extra slow which caused codecov to hang.

**Comment by hawkw** [comment]
It's possible this could be related to tarpaulin's multithreading support/lack of multithreading support -  xd009642/tarpaulin#35?

**Comment by philipc** [comment]
https://github.com/xd009642/tarpaulin/pull/59 fixed a hang that I was experiencing.

**Comment by carllerche** [comment]
Code coverage has been removed for now.
