### ISSUE TITLE
Handle Server Push Data in Client

### ISSUE THREAD

**Issue by rylio** [carllerche/h2#252]
Be able to handle data sent by the server via the http/2 push feature.

**Comment by carllerche** [comment]
Yes, this would be good!

Most of the infrastructure should already have been implemented. I think it might mostly be a question of exposing push as part of the API.

**Comment by rylio** [comment]
That is what I was thinking. If I can find the time I will work on it myself, but I need to familiarize myself with http/2 and h2. In the Go standard library there has recently been a pull request for this. [https://go-review.googlesource.com/c/net/+/85577](https://go-review.googlesource.com/c/net/+/85577).  Might be a good place to look for ideas.
