### ISSUE TITLE
Expose stream ID to application

### ISSUE THREAD

**Issue by olix0r** [carllerche/h2#289]
Problem:

Applications may want to access the underlying h2 stream ID for diagnostics, etc. As far as I know, stream IDs are not exposed in the application-facing h2 APIs.

Proposal:

In h2 servers, inbound `http::Request`s should have an `h2::StreamId` extension.

In h2 clients, `h2::client::ResponseFuture` and `h2::SendStream` should both expose a `pub fn stream_id(&self) -> h2::StreamId`; and responses satisfied from this future should have an `h2::StreamId` extension.

I'd expect `h2::StreamId` to implement at least copy and comparison traits.

**Comment by seanmonstar** [comment]
A downside is that if a user didn't need the stream ID in the Request, they've still had to pay for the hashmap allocation when h2 inserts into a new extensions set.

Since you always receive an h2 specific type as well (either `SendStream` or `RecvStream`), could they just have the accessors?

**Comment by olix0r** [comment]
@seanmonstar For servers, I take it you mean that the Recv**Body** type be extended? This all seems fine for my needs.

**Comment by seanmonstar** [comment]
Er, yes, that one! :)

**Comment by hawkw** [comment]
@olix0r 
> @seanmonstar For servers, I take it you mean that the Recv**Body** type be extended? This all seems fine for my needs.

I've started working on this in a branch and it's mostly finished, however, as far as I can tell, [there isn't currently any type called `RecvBody`](https://github.com/carllerche/h2/search?q=RecvBody&unscoped_q=RecvBody). 

However, it should be possible to add a `stream_id` accessor to `RecvStream` as @seanmonstar suggested above.
