### ISSUE TITLE
Question: Send::init_window_sz?

### ISSUE THREAD

**Issue by goffrie** [carllerche/h2#298]
I noticed that `Send::init_window_sz` is initialized with the _local_ configuration's `init_window_sz`... but should it be `config.remote_init_window_sz` (i.e. `DEFAULT_INIT_WINDOW_SIZE`) instead, or am I misunderstanding?
https://github.com/carllerche/h2/blob/78ab6167c4e3345f293a0560d0ebddda96d12dc9/src/proto/streams/send.rs#L40

**Comment by carllerche** [comment]
I believe that you are correct. Would you mind providing a PR?
