### ISSUE TITLE
There is no way to access an internal error of h2::Error that is not Kind::Proto

### ISSUE THREAD

**Issue by samamill** [carllerche/h2#310]
I have been trying to access an `io::Error` which is wrapped by `h2::Error`, but neither `reason()` nor `causeI()` expose this.

We have made the following fix to our fork to solve this issue
https://github.com/carllerche/h2/commit/7ce156d0f4acdb86e6462d88b22792971b8b021f

**Comment by carllerche** [comment]
The enum is hidden to support forwards compatibility.

The IO error can be exposed by adding the following fns:

```rust
impl Error {
    fn is_io(&self) -> bool { ... }

    fn get_io(&self) -> Option<io::Error> { ...  }

    fn into_io(self) -> Option<io::Error> { ... }
}
```

**Comment by samamill** [comment]
What would be the difference between get_io and into_io?  I imagine them returning Some(io::Error) and None for the same cases

**Comment by seanmonstar** [comment]
What you propose is what I've done in other libraries before.

**Comment by samamill** [comment]
https://github.com/carllerche/h2/pull/311
