### ISSUE TITLE
Accept stream WINDOW_UPDATE frames in reserved state

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#33]
In general, the various states in which frames can be accepted should be audited.

http://httpwg.org/specs/rfc7540.html#StreamStates

**Comment by seanmonstar** [comment]
I'm fairly sure this is working, as the `recv_window_update` only checks that the target stream is not idle.

**Comment by carllerche** [comment]
I guess this would require verifying that it currently works and add a test.
