### ISSUE TITLE
Should Connection::abrupt_shutdown cause the final poll to return an Error?

### ISSUE THREAD

**Issue by seanmonstar** [carllerche/h2#351]
If a user detects an internal error case, and calls `Connection::abrupt_shutdown(reason)`, they are supposed to still call `poll_close` until it finishes, which will ensure flushing of the GOAWAY frame. Does it really make sense to afterwards *return* an `h2::Error` with the same reason as was passed? Or should h2 assume that successfully flushing the user-initiated GOAWAY is `Ok(())`?

**Comment by carllerche** [comment]
What do you think?

**Comment by carllerche** [comment]
I assume you mean the return value of `poll_close`?

**Comment by seanmonstar** [comment]
I found it surprising that it returned an error in the most recent case that I used it.

**Comment by carllerche** [comment]
I think you are correct.
