### ISSUE TITLE
Add TCP connection adapters setting TCP_NODELAY

### ISSUE THREAD

**Issue by mzabaluev** [carllerche/h2#353]
For applications of HTTP/2.0 that don't care about HTTP/1.1 compatibility, the default socket options should be tweaked to suppress TCP-level congestion control so that flow control in HTTP/2.0 can work optimally. This is done with explicit code or custom wrappers of `tokio::tcp::ConnectFuture` and `tokio::tcp::TcpListener` in a multitude of examples and applications using `h2`.

It would therefore be useful for `h2` to provide batteries-included utilities to easily set up optimized TCP connections. This requires a dependency on tokio-tcp, but I think it's reasonable to assume that the vast majority of HTTP/2.0 applications work over TCP. The added facilities could be enabled conditionally on an optional feature if that is a concern.

**Comment by carllerche** [comment]
Thanks for opening the issue. 

The goal is for h2 to remain decoupled from specific transports. The intent is that hyper will provide these helpers. I would recommend checking there.
