### ISSUE TITLE
Strip connection level header fields

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#36]
> Such intermediaries SHOULD also remove other connection-specific header fields, such as Keep-Alive, Proxy-Connection, Transfer-Encoding, and Upgrade, even if they are not nominated by the Connection header field.

If a header frame is sent that includes a `Connection` field, it should be stripped including all fields referenced by the `Connection` field value.

**Comment by seanmonstar** [comment]
Proxies should do that, not the library. The proxies need to inspect those headers.

**Comment by carllerche** [comment]
Either way, the library has to check if those headers are set and error.

**Comment by seanmonstar** [comment]
How so? A proxy can receive those headers, and make some decisions based on them. And then it can build some new headers, that might include the same names, for the next hop.

**Comment by olix0r** [comment]
AIUI, connection headers are forbidden in h2:

> HTTP/2 does not use the Connection header field to indicate connection-specific header fields; in this protocol, connection-specific metadata is conveyed by other means. An endpoint MUST NOT generate an HTTP/2 message containing connection-specific header fields; any message containing connection-specific header fields MUST be treated as malformed (Section 8.1.2.6).

The section quoted above applies to endpoints that upgrade h1 to h2:

> This means that an intermediary transforming an HTTP/1.x message to HTTP/2 will need to remove any header fields nominated by the Connection header field, along with the Connection header field itself. Such intermediaries SHOULD also remove other connection-specific header fields, such as Keep-Alive, Proxy-Connection, Transfer-Encoding, and Upgrade, even if they are not nominated by the Connection header field.
