### ISSUE TITLE
Recv.next_stream_id should be updated in `open`

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#38]
It is currently updated in `recv_headers`, which could result in receiving a `HEADERS` frame that gets rejected (due to being malformed), then the same stream ID is received with a valid `HEADERS` frame which gets accepted.

**Comment by carllerche** [comment]
This is handled as part of #73 but it would be nice to have a test to cover the case described above.

**Comment by hawkw** [comment]
@carllerche I'd be happy to add a test for this?
