### ISSUE TITLE
Allow application to configure initial window size, etc

### ISSUE THREAD

**Issue by olix0r** [carllerche/h2#40]
gRPC clients, for instance, set an initial window of ~1MB. We should have a way to configure window sizes on clients and servers (i.e. esp prior to handshake).

**Comment by seanmonstar** [comment]
Both the Client and the Server now have builders that can currently configure:

- `initial_window_size`
- `max_frame_size`

**Comment by seanmonstar** [comment]
A client can now disable push promises.

I think that perhaps we can close this, and any individual settings required can be separate issues, since they aren't trivial things to add.
