### ISSUE TITLE
Pending push promises should be reset when a stream is closed

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#44]

**Comment by seanmonstar** [comment]
I don't quite get what situation this is describing. If push promises are sent, and then the original stream closes, it is still valid that the reserved streams can be used...

**Comment by carllerche** [comment]
@seanmonstar Yes, it is valid to use the reserved streams. However, in the case represented by this issue, the client does not pull the reserved stream handle, thus has no way to get access to the push promise.

I think this issue was created when closing the stream look `self` by ownership. This issue means that the reserved stream should be reset if the client has no way to get it.
