### ISSUE TITLE
Reset streams should cause an error when the user attempts to read frames

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#47]
* Response
* Data
* Trailers

**Comment by olix0r** [comment]
confirmed that poll_data currently returns None when the underlying connection is lost (i.e. due to a flow control error etc). 

in `h2::proto::streams::recv`
```rust

    pub fn poll_data(&mut self, stream: &mut Stream<B, P>)
        -> Poll<Option<Bytes>, proto::Error>
    {
        // TODO: Return error when the stream is reset
```

**Comment by seanmonstar** [comment]
I *think* this was fixed in #79.

**Comment by carllerche** [comment]
I guess we should confirm then close.

**Comment by seanmonstar** [comment]
Yes, there is a test for this, added in https://github.com/carllerche/h2/pull/79/files#diff-4f914e238fb524bbb31a2d7da9aa955cR228.
