### ISSUE TITLE
flow controller panic when sending data when available > window

### ISSUE THREAD

**Issue by olix0r** [carllerche/h2#77]
It's possible to panic the stream-level flow controller:

```
thread 'main' panicked at 'assertion failed: sz <= (self.window_size as WindowSize)', /home/ver/.cargo/git/checkouts/h2-5627e19d2c95dbee/d56531f/src/proto/streams/flow_control.rs:136:8
stack backtrace:
```

This is because [`FlowController::available()` is used to determine stream capacity](https://github.com/carllerche/h2/blob/master/src/proto/streams/prioritize.rs#L452-L4530), but [`FlowController::send_data` uses `FlowController::window_size()` as an upper bound](https://github.com/carllerche/h2/blob/master/src/proto/streams/flow_control.rs#L136). Because _available_ is intended to be greater than _window_size_ at times, this leads to a panic.

Changing prioritize to check `window_size()` appears to resolve this issue:
```diff
--- a/src/proto/streams/prioritize.rs
+++ b/src/proto/streams/prioritize.rs
@@ -450,7 +450,7 @@ impl<B, P> Prioritize<B, P>
                             // window.
                             //
-                            // TODO: Is this the right thing to check?
-                            let stream_capacity = stream.send_flow.available();
+                            let stream_capacity = stream.send_flow.window_size();
                             let sz = frame.payload().remaining();
 ```

It's unclear to me how _available_ is to be used on the send-side, if at all.

**Comment by carllerche** [comment]
The fact that` available` can be greater than `window_size` makes me very suspicious.

**Comment by carllerche** [comment]
This should be fixed on master.
