### ISSUE TITLE
Write documentation for h2

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#97]
The crate needs docs so that people can figure out how to use it! This issue will be used to track specific points that should be documented.

* [x] The h2 library can accept / return request / response values that are set to HTTP version 1.1.

**Comment by carllerche** [comment]
Alright, I believe that the current state of documentation is solid for an 0.1.

Thoughts?

**Comment by manifest** [comment]
Is there anything on how to use h2 with tokio runtime? I need to implement a multi threaded HTTP/2 connection pool.

**Comment by hawkw** [comment]
@manifest PR #316 updates the examples to use the new (multithreaded) `tokio` runtime. Hopefully that should give you a good starting point!

**Comment by manifest** [comment]
@hawkw thanks!
