### ISSUE TITLE
client::Stream is missing `send_reset`

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#99]
The `server` equivalent already has this function.

Originally from #75

**Comment by seanmonstar** [comment]
Is there benefit to a user calling `stream.send_reset()` versus just doing this when the stream and body are dropped?

**Comment by carllerche** [comment]
`send_reset` lets you specify a custom reason. I would guess that the RST_STREAM that happens implicitly in drop would have to be `CANCEL`.

**Comment by seanmonstar** [comment]
Ah, that's true. Looking at the list of error codes, though, I'm not sure we'd want to expose the ability to send just any reason.

**Comment by carllerche** [comment]
@seanmonstar what do you think we should vs. shouldn't?

**Comment by seanmonstar** [comment]
Shouldn't:

- NO_ERROR
- PROTOCOL_ERROR
- INTERNAL_ERROR (maybe should?)
- FLOW_CONTROL_ERROR
- SETTINGS_TIMEOUT (maybe should?)
- STREAM_CLOSED
- FRAME_SIZE_ERROR
- REFUSED_STREAM
- CANCEL
- COMPRESSION_ERROR

Should, maybe:
- CONNECT_ERROR
- ENHANCE_YOUR_CALM
- INADEQUATE_SECURITY
- HTTP_1_1_REQUIRED

**Comment by carllerche** [comment]
I think it has to do `INTERNAL_ERROR`. The others probably not.
